[window]
startup_mode = "Maximized"
dynamic_padding = true
padding = { x = 2, y = 2  }
decorations = "Full"
opacity = 0.80


[scrolling]
history = 100000

[font]
normal = { family = "Iosevka Term", style = "Regular" }
bold = { family = "Iosevka Term", style = "Bold" }
italic = { family = "Iosevka Term", style = "Italic" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic" }
size = 18

[colors.primary]
background = "#000000"
foreground = "#d8d8d8"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#4be239"
yellow = "#ffff00"
blue = "#3366ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 550
blink_timeout = 0

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "None", action = "Paste" }]
